site_wil/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
#from django.views import generic
#from django.conf.urls import patterns, include, url

from app_wil import views, models


urlpatterns = [
	url(r'^$', RedirectView.as_view(url="/tardy/")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tardy/$', views.TardyFormView.as_view()),
]

app_wil/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime
import django.utils.timezone
		
class Tardy(models.Model):
    APPOINTMENT = "Appointment"
    D_APPOINTMENT = "Dentist Appointment"
    DR_APPOINTMENT = "Dr. Appointment"
    HOLIDAY = "Holiday"
    TESTING = "Testing"
    FAMILY = "Family"
    MEETING = "Meeting"
    MEETING_CHILD = "Meeting At Child's School"
    BUS = "Missed The Bus"
    SICK = "Sick (Headache, etc.)"
    WORK = "Work"
    OTHER = "Other"
    PERIOD_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    EXCUSE_CHOICES = (
        (APPOINTMENT, 'Appointment'),
        (D_APPOINTMENT, 'Dentist Appointment'),
        (DR_APPOINTMENT, 'Dr. Appointment'),
        (HOLIDAY, 'Holiday'),
        (TESTING, 'Testing'),
        (FAMILY, 'Family'),
        (MEETING, 'Meeting'),
        (MEETING_CHILD, 'Meeting At Child\'s School'),
        (BUS, 'Missed The Bus'),
        (SICK, 'Sick (Headache, etc.)'),
        (WORK, 'Work'),
        (OTHER, 'Other'),
    )
    tardy_datetime = models.DateTimeField(default=django.utils.timezone.now())
    period = models.CharField(max_length=100, choices=PERIOD_CHOICES)
    excuse = models.CharField(max_length=100, choices=EXCUSE_CHOICES)
    note = models.BooleanField()
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = "Tardies"
    
    def __str__(self):
        return "%s: %s" % (self.name, self.date)

    @property
    def time(self):
        return self.tardy_datetime.strftime('%I:%M:%S %P')

    @property
    def date(self):
        return self.tardy_datetime.strftime('%m/%d/%Y')

app_wil/forms.py
import datetime

from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.views.generic.edit import ModelFormMixin

from app_wil import models


class AddTardyForm(forms.Form):
    name = forms.CharField(
        widget = forms.TextInput(attrs={
            'placeholder': "Full Name"
        }),
        required = True
    )
    tardy_date = forms.DateField(
        widget = SelectDateWidget(
            years = range(datetime.date.today().year,1960,-1)),
        required = True
    )
    period = forms.CharField(
        widget = forms.Select(choices = models.Tardy.PERIOD_CHOICES),
        required = True
    )
    excuse = forms.CharField(
        widget = forms.Select(choices = models.Tardy.EXCUSE_CHOICES),
        required = True
    )
    note = forms.BooleanField(
        widget = forms.CheckboxInput(),
        required = False
    )
    other = forms.CharField(
        widget = forms.TextInput(attrs={
            'placeholder': "Other Excuse"
        }),
        required = False
    )
        
    def save(self):
        info = self.cleaned_data
        new_tardy = models.Tardy.objects.create(
            name = info['name'],
            tardy_datetime = info['tardy_date'],
            period = info['period'],
            excuse = info['excuse'],
            note = info['note']
        )
        new_tardy.save()

app_wil/views.py
from django.shortcuts import render
from django.views import generic

from app_wil import models
from .forms import *


class TardyFormView(generic.FormView):
    template_name = 'form.html'
    form_class = AddTardyForm

    def get_context_data(self, *args, **kwargs):
        context = super(TardyFormView, self).get_context_data(*args, **kwargs)
        context['kwargs'] = self.kwargs
        context['request'] = self.request
        return context

    def get_form_kwargs(self):
        kwargs = super(TardyFormView, self).get_form_kwargs()
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(TardyFormView, self).form_valid(form)

    def get_success_url(self):
        return '/'

site_wil/templates/form.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Why I'm Late</title>
    <link href="/static/css/form.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
    <script type="text/javascript">
        function hideFields() {
            $("input#id_other").hide();
            $("label[for=id_other]").hide();
        }
        function showFields() {
            $("input#id_other").show();
            $("label[for=id_other]").show();
        }
        $(document).ready(function() {
            if($("select#id_excuse").val() != "Other") {
                    hideFields()
                }
            $("select#id_excuse").change(function(){
                if($("select#id_excuse").val() != "Other") {
                    hideFields()
                }
                else {
                    showFields()
                }
            });
        });
    </script>

</head>
<body>
    <nav>
        <a href="/">Home</a>
    </nav>
    <div id="header">
        <div id="title">
            <h1>Tardy Form</h1>
        </div>
        <img src="http://hiltinstitute.net/static/images/logo.png" id ="img">
    </div>
    <div id="main">
        <form action="" method="post">{% csrf_token %}
            <table id="form">
                <tbody>
                    {% for field in form %}
                        <tr>
                            <td width="30%">{{ field.label_tag }}</td>
                            <td width="70%">{{ field }}</td>
                            <td width="25%">{{ field.errors }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div style="text-align: center;">        
            <input type="submit" value="Submit" id="submit_button" />
            </div>
        </form>
    </div>
</body>
</html>